### ISSUE TITLE
Mint DOI via web service call

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/doi-service#13]
Use case is the [biocache-service issue](#12) where a download DOI is required. 

- [x] optionally accept a file to store on DOI service (use [AWS S3](https://github.com/agorapulse/grails-aws-sdk/tree/master/grails-aws-sdk-s3) ?) 
- [x] pass back DOI identifier to caller
- [ ] be fault tolerant (handle outage at either end)
- [ ] ~~service to distinguish downloads from other DOIs (so we can present list of downloads to user)~~
- [ ] store citation text
- [x] store URL to recreate the resource (original search URL)
- [x] store list of datasets contained within download (or any DOI) and to include counts (should individual datasets have their own citation text as well or provide a lookup mechanism for on-the-fly display of this - via collectory)
- [ ] store list of dataset DOIs where present (related to above item)

**Comment by ansell** [comment]
@nickdos This has been working since 2017/2018. Is it possible to close this and open specific tickets if they don't exist for features that didn't make it into that release (Fault-Tolerance on each step is a sub-epic(?) that is being tracked in #17 for example)

**Comment by nickdos** [comment]
Yes, will close it - any future enhancements will be via new issue.
